name: duole
description: "Duole Game."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  percent_indicator: ^4.2.3
  get: ^4.6.6
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: HarmonyOS
      fonts:
        - asset: fonts/HarmonyOS-Sans-SC-Regular.ttf
        - asset: fonts/HarmonyOS-Sans-SC-Bold.ttf
          weight: 900
        - asset: fonts/HarmonyOS-Sans-SC-Medium.ttf
          weight: 500
    - family: TimebombBb
      fonts:
        - asset: fonts/TimebombBb.ttf